### ISSUE TITLE
Google Play Services version conflict with Pushwoosh

### ISSUE THREAD

**Issue by jamesar-dev** [Pushwoosh/pushwoosh-unity#14]
Hey guys,

 As I've seen on here and elsewhere around the internet, I'm having some issues between the version of play services that Pushwoosh wants to use (8.4.0) and the latest version of the google play services plugin for Unity (which wants to use version 9.4.0). 

 What I've done is try to delete the older versions and roll with the new version, 9.4.0. Everything seems to compile fine, and I don't run into any dex errors. When running on the device, I can make it all the way to the Pushwoosh registration before the app crashes. 

 The device log produces the message I have pasted below, which I assume is caused by something in the Pushwoosh sdk trying to access a component of an older version of the google play services. 

 My question is this - Is there a definitive fix for using the latest version of play services with the Pushwoosh Unity SDK? Thanks ahead of time for the help!

`08-24 11:25:01.587 8292-8471/? E/AndroidRuntime: FATAL EXCEPTION: IntentService[GCMRegistrationService]
                                                 Process: com.project.example, PID: 8292
                                                 java.lang.Error: FATAL EXCEPTION [IntentService[GCMRegistrationService]]
                                                 Unity version     : 5.3.5f1
                                                 Device model      : LGE Nexus 5
                                                 Device fingerprint: google/hammerhead/hammerhead:6.0/MRA58N/2289998:user/release-keys`

```
                                             `Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/iid/InstanceID;
                                                 at com.pushwoosh.GCMRegistrationService.a(Unknown Source)
                                                 at com.pushwoosh.GCMRegistrationService.onHandleIntent(Unknown Source)
                                                 at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                 at android.os.Looper.loop(Looper.java:148)
                                                 at android.os.HandlerThread.run(HandlerThread.java:61)
                                              Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.iid.InstanceID" on path: DexPathList[[zip file "/data/app/com.project.example-1/base.apk"],nativeLibraryDirectories=[/data/app/com.project.example-1/lib/arm, /data/app/com.project.example-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
                                                 at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                 at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                 at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                 at com.pushwoosh.GCMRegistrationService.a(Unknown Source) 
                                                 at com.pushwoosh.GCMRegistrationService.onHandleIntent(Unknown Source) 
                                                 at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66) 
                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                 at android.os.Looper.loop(Looper.java:148) 
                                                 at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                Suppressed: java.lang.ClassNotFoundException: com.google.android.gms.iid.InstanceID
                                                 at java.lang.Class.classForName(Native Method)
                                                 at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                 at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                 at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                        ... 7 more
                                              Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available`
```

**Comment by DimanAM** [comment]
`com.google.android.gms.iid.InstanceID` was part of `play-services-gcm-8.4.0.aar` library. But
`play-services-gcm` library was split into `play-services-gcm` and `play-services-iid` since 9.0.0. So you also need to include `play-services-iid-9.4.0.aar` if you want to update play services.

**Comment by jamesar-dev** [comment]
Wonderful! That totally fixed it. Thanks a ton for the help!

**Comment by joaquingrech** [comment]
yeah guys but you should already update to 9.4 it's been over a year with that version. Also the new system provokes lot of dex errors because the field limit is very close. If you add pushwoosh and another .arr or jar plugin, you'll an error (and that limit wasn't hit with the previous version of the plugin). Forcing us to choose between the other plugins and pushwoosh. Obviously I had to remove pushwoosh because I can't remove the other plugins which are not optional.
This is the error you get, you really need to reduce the field count on your package.
`CommandInvokationFailure: Unable to convert classes into dex format.
D:/Java/jdk1.8.0_60\bin\java.exe -Xmx2048M -Dcom.android.sdkmanager.toolsdir="E:/android-sdk\tools" -Dfile.encoding=UTF8 -jar "D:\Unity 5.0.0\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\sdktools.jar" -

stderr[

trouble writing output: Too many field references: 65718; max is 65536.
You may try using --multi-dex option.

**Comment by shaders** [comment]
Why multi-dex option is not the case?

https://developer.android.com/studio/build/multidex.html

**Comment by joaquingrech** [comment]
i don't think there is an option to set that on unity, i googled it with no luck. And since the package will incluse also a bunch of google play .aar files, the field references go up pretty quick

**Comment by shaders** [comment]
Yes unfortunately Unity does not support this. I'll see what we can do.

**Comment by joaquingrech** [comment]
also the android-support-v4 jar file is problematic... since it conflicts with the default support-v4 from google play services and that is also required by other plugins

**Comment by joaquingrech** [comment]
any updates released soon? everyone with unity packages is in trouble since you've updated everything else but this

**Comment by shaders** [comment]
updated via https://github.com/Pushwoosh/pushwoosh-unity/commit/92437822fb5605e178a29012fab3562ad66a9495
