### ISSUE TITLE
Sample project Android build doesn't run when built with fresh checkout using Unity 2017.4 LTS release.

### ISSUE THREAD

**Issue by JimmyDeemo** [Pushwoosh/pushwoosh-unity#36]
Steps:

1. Checkout the repo.
2. Load sample project using Unity 2017.4.8f1.
3. Select `Custom` --> `Build Android`.
4. Install .apk via `adb`.
5. Run game, notice crash.

Log
[log.txt](https://github.com/Pushwoosh/pushwoosh-unity/files/2262997/log.txt)

Main error:
```
--------- beginning of crash
08-06 15:44:38.387 30833 30833 E AndroidRuntime: FATAL EXCEPTION: main
08-06 15:44:38.387 30833 30833 E AndroidRuntime: Process: com.pushwoosh.demoapp, PID: 30833
08-06 15:44:38.387 30833 30833 E AndroidRuntime: java.lang.RuntimeException: Unable to get provider com.pushwoosh.gcm.GcmInitProvider: java.lang.IllegalStateException: You must add "implementation 'com.google.android.gms:play-services-gcm:11.+'" line to your app build.gradle.
08-06 15:44:38.387 30833 30833 E AndroidRuntime: 	at android.app.ActivityThread.installProvider(ActivityThread.java:6087)
08-06 15:44:38.387 30833 30833 E AndroidRuntime: 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:5655)
08-06 15:44:38.387 30833 30833 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5594)
08-06 15:44:38.387 30833 30833 E AndroidRuntime: 	at android.app.ActivityThread.-wrap2(ActivityThread.java)
08-06 15:44:38.387 30833 30833 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1640)
08-06 15:44:38.387 30833 30833 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:110)
08-06 15:44:38.387 30833 30833 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:203)
08-06 15:44:38.387 30833 30833 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6361)
08-06 15:44:38.387 30833 30833 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-06 15:44:38.387 30833 30833 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
08-06 15:44:38.387 30833 30833 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
08-06 15:44:38.387 30833 30833 E AndroidRuntime: Caused by: java.lang.IllegalStateException: You must add "implementation 'com.google.android.gms:play-services-gcm:11.+'" line to your app build.gradle.
08-06 15:44:38.387 30833 30833 E AndroidRuntime: 	at com.pushwoosh.gcm.a.b.b(Unknown Source)
08-06 15:44:38.387 30833 30833 E AndroidRuntime: 	at com.pushwoosh.gcm.a.b.a(Unknown Source)
08-06 15:44:38.387 30833 30833 E AndroidRuntime: 	at com.pushwoosh.gcm.GcmInitProvider.a(Unknown Source)
08-06 15:44:38.387 30833 30833 E AndroidRuntime: 	at com.pushwoosh.gcm.GcmInitProvider.onCreate(Unknown Source)
08-06 15:44:38.387 30833 30833 E AndroidRuntime: 	at android.content.ContentProvider.attachInfo(ContentProvider.java:1769)
08-06 15:44:38.387 30833 30833 E AndroidRuntime: 	at android.content.ContentProvider.attachInfo(ContentProvider.java:1744)
08-06 15:44:38.387 30833 30833 E AndroidRuntime: 	at android.app.ActivityThread.installProvider(ActivityThread.java:6084)
08-06 15:44:38.387 30833 30833 E AndroidRuntime: 	... 10 more
08-06 15:44:38.387 30833 30833 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: com.google.android.gms.gcm.GcmReceiver
08-06 15:44:38.387 30833 30833 E AndroidRuntime: 	at java.lang.Class.classForName(Native Method)
08-06 15:44:38.387 30833 30833 E AndroidRuntime: 	at java.lang.Class.forName(Class.java:400)
08-06 15:44:38.387 30833 30833 E AndroidRuntime: 	at java.lang.Class.forName(Class.java:326)
08-06 15:44:38.387 30833 30833 E AndroidRuntime: 	... 17 more
08-06 15:44:38.387 30833 30833 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.gcm.GcmReceiver" on path: DexPathList[[zip file "/data/app/com.pushwoosh.demoapp-1/base.apk"],nativeLibraryDirectories=[/data/app/com.pushwoosh.demoapp-1/lib/arm, /data/app/com.pushwoosh.demoapp-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
08-06 15:44:38.387 30833 30833 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
08-06 15:44:38.387 30833 30833 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
08-06 15:44:38.387 30833 30833 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
08-06 15:44:38.387 30833 30833 E AndroidRuntime: 	... 20 more
```

**Comment by JimmyDeemo** [comment]
My apologies, it appears that I had some mixed up settings. Following the steps with a clean repo works fine.
