### ISSUE TITLE
Crash on Amazon

### ISSUE THREAD

**Issue by reflexing** [Pushwoosh/pushwoosh-unity#65]
Crash on Amazon device with Pushwoosh Unity Plugin 6.1.2:

`2022-07-14 17:42:05.281 18881-18881/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: redacted.tld, PID: 18881
    java.lang.RuntimeException: Unable to start receiver com.pushwoosh.PushAmazonReceiver: java.lang.IllegalArgumentException: No such service ComponentInfo{redacted.tld/com.pushwoosh.PushAmazonHandlerJob}
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3415)
        at android.app.ActivityThread.access$1200(ActivityThread.java:207)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1670)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:211)
        at android.app.ActivityThread.main(ActivityThread.java:6740)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.IllegalArgumentException: No such service ComponentInfo{redacted.tld/com.pushwoosh.PushAmazonHandlerJob}
        at android.os.Parcel.createException(Parcel.java:1954)
        at android.os.Parcel.readException(Parcel.java:1918)
        at android.os.Parcel.readException(Parcel.java:1868)
        at android.app.job.IJobScheduler$Stub$Proxy.enqueue(IJobScheduler.java:215)
        at android.app.JobSchedulerImpl.enqueue(JobSchedulerImpl.java:53)
        at com.amazon.device.messaging.JobIntentService$JobWorkEnqueuer.enqueueWork(JobIntentService.java:361)
        at com.amazon.device.messaging.JobIntentService.enqueueWork(JobIntentService.java:565)
        at com.amazon.device.messaging.ADMMessageReceiver.onReceive(ADMMessageReceiver.java:115)
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3406)
        at android.app.ActivityThread.access$1200(ActivityThread.java:207) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1670) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:211) 
        at android.app.ActivityThread.main(ActivityThread.java:6740) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
     Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.job.JobSchedulerService$JobSchedulerStub.enforceValidJobRequest(JobSchedulerService.java:2560)
        at com.android.server.job.JobSchedulerService$JobSchedulerStub.enqueue(JobSchedulerService.java:2650)
        at android.app.job.IJobScheduler$Stub.onTransact(IJobScheduler.java:82)
        at android.os.Binder.execTransact(Binder.java:731)`

Solved by adding to AndroidManifest.xml:

`<service android:name="com.pushwoosh.PushAmazonHandlerJob"
     		android:permission="android.permission.BIND_JOB_SERVICE"
		android:exported="true"/>`

**Comment by wfhm** [comment]
@reflexing Thanks for reporting this. Will be fixed with the next release.

**Comment by wfhm** [comment]
@reflexing Fixed in 6.1.3. The PushAmazonHandlerJob service will now properly be declared when Pushwoosh SDK's manifest is merged.
